---
# tasks file for common
- name: Upgrading all packages
  apt:
    upgrade: 'yes'
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Update all packages (Ubuntu based)
  apt:
    name: "*"
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Upgrading all packages (RHEL based)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"