---

- name: Add users
  user: 
    name: "{{ item.name }}" 
    comment: "{{ item.comment }}" 
    state: "{{ item.state }}"
    shell: /bin/zsh
    groups: wheel
    append: yes
    createhome: yes
    password: "{{ item.password}}"
  with_items: "{{ ssh_users }}"
  ignore_errors: true

- name: Add ssh pub keys users
  authorized_key: 
    user: "{{ item.name }}" 
    key: "{{ item.key }}"
  with_items: "{{ ssh_users }}"
  ignore_errors: true

- name: Add ssh pub keys user deployer
  authorized_key: 
    user: deployer 
    key: "{{ item.key }}"
    manage_dir: yes
    path: /opt/deployer/.ssh/authorized_keys
    state: present
  with_items: "{{ ssh_users }}"
  ignore_errors: true