---
#ENSURE INSTALL IPTABLES
- name: Install the `iptables` package
  package:
    name: iptables
    state: latest

- name: Flush existing firewall rules
  iptables:
    flush: true

#GENERAL RULES
- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

#IP TABLES RULES
- name: Firewall rule - BLOCK port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp

# - name: Firewall rule - BLOCK port 22/SSH traffic
#   iptables:
#     chain: INPUT
#     destination_port: 22
#     jump: DROP
#     protocol: tcp

- name: Firewall rule - allow port SSH traffic
  iptables:
    chain: INPUT
    destination_port: "{{ ssh_port }}"
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - Accept new connection from port SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.

# # Reject tcp with tcp-reset
# - iptables:
#     chain: INPUT
#     protocol: tcp
#     reject_with: tcp-reset
#     ip_version: ipv4

# Set tcp flags
# Allow new incoming SYN packets on TCP.
# - iptables:
#     chain: INPUT
#     protocol: tcp
#     ctstate: NEW
#     syn: match
#     jump: ACCEPT

- name: Firewall rule - Drop some possible attacks
  iptables:
    chain: INPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN

# Tag all outbound tcp packets with DSCP DiffServ class CS1
- name: Tag all outbound tcp packets with DSCP DiffServ class CS1
  iptables:
    chain: OUTPUT
    jump: DSCP
    table: mangle
    set_dscp_mark_class: CS6
    protocol: tcp

# Set tcp flags
- name: Set tcp flags
  iptables:
    chain: INPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN

- name: Set tcp flags
  iptables:
    chain: OUTPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN

#IP TABLES DROP ALL       
- name: Firewall rule - drop any traffic without rule
  iptables:
    chain: INPUT
    jump: DROP
    rule_num: '100'    
