---
#ENSURE INSTALL IPTABLES
- name: Install the `iptables` package
  package:
    name: iptables
    state: latest
  tags: iptables

- name: Flush existing firewall rules
  iptables:
    flush: true
  tags: iptables

#GENERAL RULES
- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - allow output established connections
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

## PING
- name: Firewall rule - ALLOW port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp

- name: Firewall rule - ALLOW port ping traffic output
  iptables:
    chain: OUTPUT
    jump: ACCEPT
    protocol: icmp

## SSH
- name: Firewall rule - allow port SSH traffic
  iptables:
    chain: INPUT
    destination_port: "{{ ssh_port }}"
    jump: ACCEPT
    protocol: tcp
  tags: iptables

- name: Firewall rule - Accept new connection from port SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  tags: iptables

## DNS
# - name: Firewall rule - Accept new connection from port DNS UDP
#   iptables:
#     chain: OUTPUT
#     protocol: udp
#     destination_port: "53"
#     ctstate: NEW
#     jump: ACCEPT
#     comment: Accept new Outbound DNS connections.
#   tags: iptables

# - name: Firewall rule - Accept new connection from port DNS TCP
#   iptables:
#     chain: OUTPUT
#     protocol: tcp
#     destination_port: "53"
#     ctstate: NEW
#     jump: ACCEPT
#     comment: Accept new Outbound DNS connections.
#   tags: iptables

## HTTP
# - name: Firewall rule - Accept new connection from port 80
#   iptables:
#     chain: OUTPUT
#     protocol: tcp
#     destination_port: "80"
#     ctstate: NEW
#     jump: ACCEPT
#     comment: Accept new Outbound HTTP connections.
#   tags: iptables

# - name: Firewall rule - Accept new connection from port 443
#   iptables:
#     chain: OUTPUT
#     protocol: tcp
#     destination_port: "443"
#     ctstate: NEW
#     jump: ACCEPT
#     comment: Accept new Outbound HTTPS connections.
#   tags: iptables

# SECURITY RULES
- name: Reject tcp with tcp-reset
  iptables:
    chain: INPUT
    protocol: tcp
    reject_with: tcp-reset
    ip_version: ipv4
  tags: iptables

- name: Allow new incoming SYN packets on TCP.
  iptables:
    chain: INPUT
    protocol: tcp
    ctstate: NEW
    syn: match
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - Drop some possible attacks
  iptables:
    chain: INPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
  tags: iptables

# Tag all outbound tcp packets with DSCP DiffServ class CS1
- name: Tag all outbound tcp packets with DSCP DiffServ class CS1
  iptables:
    chain: OUTPUT
    jump: DSCP
    table: mangle
    set_dscp_mark_class: CS6
    protocol: tcp
  tags: iptables

# Set tcp flags
- name: Set tcp flags
  iptables:
    chain: INPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
  tags: iptables

- name: Set tcp flags
  iptables:
    chain: OUTPUT
    jump: DROP
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
  tags: iptables

#IP TABLES DROP ALL       
# - name: Firewall rule - drop any INPUT traffic without rule
#   iptables:
#     chain: INPUT
#     jump: DROP
#     rule_num: '100'    
#   tags: iptables

# - name: Firewall rule - drop any OUTPUT traffic without rule
#   iptables:
#     chain: OUTPUT
#     jump: DROP
#     rule_num: '100'    
#   tags: iptables

# - name: Firewall rule - drop any FORWARD traffic without rule
#   iptables:
#     chain: FORWARD
#     jump: DROP
#     rule_num: '100'    
#   tags: iptables