---

- name: configure system settings, file descriptors and number of threads
  pam_limits:
        domain: '*'
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
  with_items:
        - { limit_type: '-', limit_item: 'nofile', value: 65536 }
        - { limit_type: '-', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'soft', limit_item: 'nofile', value: 60000 }
        - { limit_type: 'hard', limit_item: 'nofile', value: 80000 }
- name: reload settings from all system configuration files
  shell: sysctl --system