---
- name: Create Certs folders
  file: path={{ item.path }} state=directory mode="a+rw"
  with_items:
      - { path: '/etc/ssl/crt/' }
      - { path: '/etc/ssl/private/' }
      - { path: '/etc/ssl/csr/' }

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/ssl/private/{{ ansible_fqdn }}.pem

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/ssl/csr/{{ ansible_fqdn }}.csr
    privatekey_path: /etc/ssl/private/{{ ansible_fqdn }}.pem
    common_name: "{{ ansible_fqdn }}"
  ignore_errors: true

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/{{ ansible_fqdn }}.crt
    privatekey_path: /etc/ssl/private/{{ ansible_fqdn }}.pem
    csr_path: /etc/ssl/csr/{{ ansible_fqdn }}.csr
    provider: selfsigned
  ignore_errors: true

- name: Copy SSL enterprise certificates 
  copy:
      src: "{{ role_path }}/files/ssl"
      dest: /etc/ssl/
      owner: root
      mode: 600
      remote_src: no
      directory_mode: yes
  ignore_errors: true
