# UPDATE
- apt:
    name: "*"
    state: latest
  when: ansible_distribution == 'Ubuntu'

# UPGRADE
- apt:
    upgrade: 'yes'
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
